### ISSUE TITLE
Tests broken, again

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/dinglehopper#102]
https://github.com/qurator-spk/dinglehopper/actions/runs/7285741554/job/19868158221?pr=101

May be because it was a PR.

**Comment by mikegerber** [comment]
Tests ran fine after merging, so this was something related to that it was a PR.

**Comment by sadra-barikbin** [comment]
@mikegerber , Failing tests in PRs is seemingly due to the fact that workflows triggered by `pull_request` event are not granted access to do certain things, e.g. to create checks as does the `test-reporter` here:
https://github.com/qurator-spk/dinglehopper/blob/d3fb3f96cf923e7c1935f4501bd8a949e53abf80/.github/workflows/test.yml#L70-L76

We could add a separate workflow file triggered by `workflow_run` which could be granted access to create checks and move the above step there. Please see [this](https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories) and [this](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/). I would make the PR if you will.

**Comment by mikegerber** [comment]
@sadra-barikbin Yes, exactly! I will take my time to review this though, dangerous territory ;)

**Comment by mikegerber** [comment]
Should be fixed with @sadra-barikbin's PR #103, merged in 788868b!
