### ISSUE TITLE
Skip when there is no file matching the pageId

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/dinglehopper#34]
`ocrd-dinglehopper` should issue a warning and skip a page if there is no matching GT or OCR file for a page.

Reported by @mnoelte in Gitter:
https://gitter.im/OCR-D/Lobby?at=5f76f0750dbbcf3dfa50648f

**Comment by bertsky** [comment]
See [here](https://github.com/OCR-D/ocrd_segment/blob/aadbc7b33ebceee320cd1a8b13c2392a389476a2/ocrd_segment/evaluate.py#L64-L92) for a recipe. You can omit the fallback search via matching `imageFilename` for efficiency.
Then use something like [this](https://github.com/OCR-D/ocrd_segment/blob/aadbc7b33ebceee320cd1a8b13c2392a389476a2/ocrd_segment/evaluate.py#L39-L52) instead of the typical loop around `self.input_files`...

**Comment by mikegerber** [comment]
Side note: `files[0]` in that code might fail now that `find_files()` returns an iterator.

**Comment by bertsky** [comment]
> Side note: `files[0]` in that code might fail now that `find_files()` returns an iterator.

Hell yes, that broke all our multi-input-fileGrp processors!

Must replace with `find_all_files` ASAP

**Comment by mikegerber** [comment]
> Must replace with `find_all_files` ASAP

Is that an API function? https://ocr-d.de/core/search.html?q=find_all_files returns nothing

**Comment by bertsky** [comment]
> Is that an API function? https://ocr-d.de/core/search.html?q=find_all_files returns nothing

It is. @kba I guess the apidoc must be regenerated?

@mikegerber `ocrd_models.ocrd_mets.OcrdMets.find_all_files`

**Comment by kba** [comment]
> It is. @kba I guess the apidoc must be regenerated?

yep 😊 on it.
