### ISSUE TITLE
Improve performance when calculating sequence alignment

### ISSUE THREAD

**Issue by b2m** [qurator-spk/dinglehopper#56]
Dinglehopper is using a custom Python implementation of the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) to calculate, score and show an alignment of two given texts.

According to my performance analysis done for #47 the `distance` and `editops` functions of this custom implementation is the main bottleneck when comparing explicitly bad or big OCR results.

In #48 I proposed to use the C based [python-Levenshtein](https://pypi.org/project/python-Levenshtein/) as a replacement, which we discarded for the following reasons:

1. No support for aligning sequences of words (see [comment by @mikegerber](https://github.com/qurator-spk/dinglehopper/pull/48#issuecomment-818021820)).
2. Currently [no active maintenance](https://github.com/ztane/python-Levenshtein#maintainer-wanted).
3. Viral license (GPL 2)

One alternative and fast implementation for distance calculation is [RapidFuzz](https://github.com/maxbachmann/RapidFuzz/), where @maxbachmann already started to adress the issue of  the distance calculation for arbitrary sequences in maxbachmann/RapidFuzz#100.

At the moment [RapidFuzz](https://github.com/maxbachmann/RapidFuzz/) is not supporting the calculcation of edit operations (see [comment by @maxbachmann](https://github.com/qurator-spk/dinglehopper/pull/48#issuecomment-818577319)).

**Comment by mikegerber** [comment]
Just to be thorough:

>     1. No support for aligning sequences of words (see [comment by @mikegerber](https://github.com/qurator-spk/dinglehopper/pull/48#issuecomment-818021820)).

No support for arbitrary data, I would say. Technically, we align*/measure distance between a. sequences of grapheme clusters (which is not always the same as strings) and b. sequences of words.

* I would consider aligning as equivalent to "editops"

Technically I believe any sequence alignment implementation would do if it a. supports substitutions and b. is optimal in the sense that it gives a shortest possible alignment. If we have that I believe we could just count for the edit distance calculation.

However I can **imagine** dropping the alignment requirement if the user chooses to do that to improve the speed of calculating the metrics, as there are implementations that can do that calculation more efficiently (speed/memory) without providing the alignemnt. In my experience it is however incredibly important to have a manual look on the alignment (= the differences report) to get a sense of the problems and this is even more important with larger texts. (As I understand it, this could be done with RapidFuzz already because of optimizations)

The second thing I can **imagine** is considering more efficient sequence alignment algorithms, that can easily handle larger texts. This is more problematic, as this is an evaluation tool. I deliberately chose an easily auditable textbook implementation of an optimal algorithm (optimal in the sense of shortest alignment = shortest edit distance) and I would hate to introduce vagueness in the sense of "This could be the CER but we don't know it for sure because of worst case behaviour of the algorithm". But maybe there is no way around this.

For now, the best short term outcome would be if we get a "reasonable" performance for real world data I've seen. @cneud reported hours of runtime and 40 GB of memory usage for a newspaper page (a lot of text!) - That is certainly not "reasonable". I'll see if the license of the data allows uploading it. (The memory usage comes from 68188 characters of GT text, assuming roughly the same size for the OCR text and 64 bits to store an element of the Levenshtein matrix gives 68188*68188*8/(1024*1024*1024) =~ 34 GB  of memory usage...)

**Comment by mikegerber** [comment]
Another possibility: Efficiently calculate an optimal(!) CER, but the alignment might by calculated by some more efficient algorithm (not optimal, but fast)

**Comment by maxbachmann** [comment]
> (The memory usage comes from 68188 characters of GT text, assuming roughly the same size for the OCR text and 64 bits to store an element of the Levenshtein matrix gives 68188x68188x8/(1024x1024x1024) =~ 34 GB of memory usage...)

## No editops required
For any texts where the editops are not required the Levenshtein distance can be implemented using linear memory.

## Performance more important than memory usage
For cases where the Levenshtein matrix is actually required it could choose the type based upon `max(len1, len2)`
- <= 255 -> uin8_t
- <= 65535 -> uint16_t
- <= 4294967295 -> uint32_t
- else uint64_t

Most PCs will not even have enough memory to ever require uint64_t. E.g. in your example this would reduce the memory requirement by 50%.

## memory usage more important than performance
It would be possible to be even more aggressive by creating a specialized container, which always has submatrices using the smaller datatype. This could reduce the requirement for a 68188x68188 matrix to:
- (68188*68188 - 65535*65535) * 4 + (65535*65535 - 255*255) * 2 + 255*255 = 10 Gb
This third approach could be e.g. selected either by an argument, or when the malloc for the faster implementation fails

**Comment by maxbachmann** [comment]
> At the moment RapidFuzz is not supporting the calculcation of edit operations (see comment by @maxbachmann).

@mikegerber @b2m In the Levenshtein matrix there are often multiple optimal paths, while editops will just return one. Is there any reason to prefer one path over another? The simplest way would be:

```
if (diagonal == current)      -> no operation
if (diagonal == current -1) -> Substitution
if (left == current - 1)         -> Insertion
if (above == current - 1)    -> Deletion
```

python-Levenshtein extends this slightly by preferring multiple similar operations in a row:

```
if (last_operation == Insertion and left == current - 1)         -> Insertion
if (last_operation == Deletion and above == current - 1)    -> Deletion

if (diagonal == current)      -> no operation
if (diagonal == current -1) -> Substitution
if (left == current - 1)         -> Insertion
if (above == current - 1)    -> Deletion
```

I guess the reason for this path is, that python-Levenshtein allows the conversion into opcodes, which always specify a range for which the operation is used -> Multiple similar operations in a row can be combined into a single range, which results in a shorter list.

Is there any reason to prefer any of the paths?

**Comment by maxbachmann** [comment]
> @maxbachmann already started to adress the issue of the distance calculation for arbitrary sequences in maxbachmann/RapidFuzz#100.

This is now supported in the next release (implemented just not released yet).
```python
> from rapidfuzz import string_metric
> string_metric.levenshtein(["aaaa", "bbbb"], ["aaaa", "cccc"])
1
```
note that this operates on the hashes of the strings. So this is the same as:
```python
> from rapidfuzz import string_metric
> string_metric.levenshtein([hash("aaaa"), hash("bbbb")], [hash("aaaa"), hash("cccc")])
1
```
So when two strings produce the same hash value they will be considered as equivalent

**Comment by b2m** [comment]
@maxbachmann I have not checked the python-Levenshtein original code, but the `last_operation` seems like a performance tweak.

Using hashing to be able to compare "arbitrary" sequences sounds sensible to me. Yes there will be collisions, and there are detailed StackOverflow questions/answers going into detail on when this happens.

From a Python programmers perspective I would worry about comparing sequences with object that do not implement a proper `__hash__` method.

**Comment by maxbachmann** [comment]
> I have not checked the python-Levenshtein original code, but the last_operation seems like a performance tweak.

In which cases would this help performance. My guess was that it has something to do with these weird conversions in python-Levenshtein from `editops to opcodes` and `editops to matching_blocks` to make them as similar as possible to the results from difflib (Even though at least matching_blocks is completely broken and will not return the correct results in many cases).

I will probably add another function to get the Levenshtein matrix in a space optimized way as well using some of the methods described above.

> From a Python programmers perspective I would worry about comparing sequences with object that do not implement a proper __hash__ method.

The only alternative would be using __eq__. However
1) This would not work with all algorithms (many of the implementations rely on the elements being compared to be numbers)
2) even algorithms which could use __eq__ like the normal O(N*M) Levenshtein implementation would become painfully slow, since __eq__ is
  - a Python call which adds tons of overhead
  - probably O(N) which causes the algorithm to have cubic runtime
 
Note that one special case is, that I directly use the corresponding unicode code-point for strings with a length of 1, so the following works:
```python
> from rapidfuzz import string_metric
> string_metric.levenshtein("aaaa", ["a", "a", "a", "a"])
0
> string_metric.levenshtein("aaaa", [ord("a"), ord("a"), ord("a"), ord("a")])
0
```

**Comment by maxbachmann** [comment]
@b2m I released v1.5.0 of rapidfuzz yesterday, which includes the support for other types than string and editops:
```python
>>> from rapidfuzz.string_metric import levenshtein_editops
>>> for tag, src_pos, dest_pos in levenshtein_editops("qabxcd", "abycdf"):
...    print(("%7s s1[%d] s2[%d]" % (tag, src_pos, dest_pos)))
  delete s1[1] s2[0]
replace s1[4] s2[3]
   insert s1[6] s2[6]
```

**Comment by b2m** [comment]
> I have not checked the python-Levenshtein original code, but the `last_operation` seems like a performance tweak.

Addition: performance tweak in the sense of determining ranges of inserts or deletes **while** determining the type of edit operation. The alternative would be to have a second pass through all the edit operations.

> I released v1.5.0 of rapidfuzz yesterday

Thx for the heads up... should go to @mikegerber as he is the maintainer of this library.

> support all sequences of hashable objects and editops

I like the simplicity of the interface and the returned data!

**Comment by mikegerber** [comment]
Awesome, I have been on vacation and I will check this out soon!

**Comment by mikegerber** [comment]
This is done, and with #72 (also in milestone 1.0) the remaining issue (duplicate calls) should be done, too.
